# 错误处理运算符

&emsp;&emsp;您可能熟悉在 try-catch 块中处理异常的几种方法。最值得注意的是，这些包括以下内容：

- 捕获并返回静态默认值。
- 使用回退方法捕获并执行替代路径。
- 捕获并动态计算回退值。
- 捕获、包装到BusinessException，然后重新抛出。
- 捕获、记录特定于错误的消息，然后重新抛出。
- 使用finally块清理资源或Java7“trywithresource”构造。

&emsp;&emsp;所有这些在 Reactor 中都以错误处理运算符的形式存在。在研究这些运算符之前，我们首先要在反应链和 try-catch 块之间建立一个并行关系。

&emsp;&emsp;订阅时，链末尾的 onError 回调类似于一个 catch 块。在那里，如果抛出异常，执行将跳到catch ，如以下示例所示：

```java
Flux<String> s = Flux.range(1, 10)
    .map(v -> doSomethingDangerous(v))  // 1 执行可以抛出异常的转换。
    .map(v -> doSecondTransform(v));  // 2 如果一切顺利，将执行第二次转换。(显然前面不会顺序)
s.subscribe(value -> System.out.println("RECEIVED " + value), // 3 每个成功转换的值都被打印出来。
            error -> System.err.println("CAUGHT " + error)  // 4 如果出现错误，序列将终止并显示一条错误消息。
);
```

&emsp;&emsp;前面的示例在概念上类似于以下 try-catch 块：

```java
try {
    for (int i = 1; i < 11; i++) {
        String v1 = doSomethingDangerous(i);  // 1 如果这里抛出异常……
        String v2 = doSecondTransform(v1);  // 2 …循环的其余部分被跳过…
        System.out.println("RECEIVED " + v2);
    }
} catch (Throwable t) {
    System.err.println("CAUGHT " + t);  // 3 …​ and the execution goes straight to here.

}
```

&emsp;&emsp;现在我们已经建立了一个并行，我们可以看看不同的错误处理案例和它们的等效运算符。

---

### 静态回退值

&emsp;&emsp;“捕捉并返回静态默认值”的等价物是 onErrorReturn。以下示例显示了如何使用它：

```java
try {
  return doSomethingDangerous(10);
}
catch (Throwable error) {
  return "RECOVERED";
}
```

&emsp;&emsp;以下示例显示了 Reactor 等效项：

```java
Flux.just(10)
    .map(this::doSomethingDangerous)
    .onErrorReturn("RECOVERED");
```

&emsp;&emsp;您还可以选择对异常应用谓词来决定是否恢复，如以下示例所示：

```java
Flux.just(10)
    .map(this::doSomethingDangerous)
    .onErrorReturn(e -> e.getMessage().equals("boom10"), "recovered10");  // 1 仅在异常消息为“boom10”时恢复
```

---

### 捕获并吞下错误

&emsp;&emsp;如果您甚至不想用回退值替换异常，而是忽略它并只传播到目前为止已经生成的元素，那么您实际上想要的是用 `onComplete` 信号替换 `onError` 信号。这可以通过 `onErrorComplete` 运算符来完成：

```java
Flux.just(10,20,30)
    .map(this::doSomethingDangerousOn30)
    .onErrorComplete();  // 1 通过将 onError 变成 onComplete 来恢复
```

&emsp;&emsp;与 `onErrorReturn` 一样，`onErrorComplete` 有一些变体，可以让您根据异常的类或 Predicate 过滤要回退的异常。

---

### 回退方法

&emsp;&emsp;如果您想要多个默认值并且您有另一种（更安全的）处理数据的方式，您可以使用 `onErrorResume`。这相当于“使用回退方法捕获并执行替代路径”。

&emsp;&emsp;例如，如果您的标称进程正在从外部和不可靠的服务中获取数据，但您还保留了相同数据的本地缓存，这些数据可能有点过时但更可靠，您可以执行以下操作：

```java
String v1;
try {
  v1 = callExternalService("key1");
}
catch (Throwable error) {
  v1 = getFromCache("key1");
}

String v2;
try {
  v2 = callExternalService("key2");
}
catch (Throwable error) {
  v2 = getFromCache("key2");
}
```

&emsp;&emsp;以下示例显示了 Reactor 等效项：

```java
Flux.just("key1", "key2")
    .flatMap(k -> callExternalService(k)  // 1 对于每个键，异步调用外部服务。
        .onErrorResume(e -> getFromCache(k)) // 2 如果外部服务调用失败，则回退到该键的缓存。请注意，无论源错误 e 是什么，我们总是应用相同的回退。
    );
```

&emsp;&emsp;与 `onErrorReturn` 一样，`onErrorResume` 有一些变体，可以让您根据异常的类或 `Predicate` 过滤要回退的异常。它采用 `Function` 的事实还允许您根据遇到的错误选择不同的回退序列来切换。以下示例显示了如何执行此操作：

```java
Flux.just("timeout1", "unknown", "key2")
    .flatMap(k -> callExternalService(k)
        .onErrorResume(error -> { // 1 该功能允许动态选择如何继续
            if (error instanceof TimeoutException) // 2 如果源超时，则命中本地缓存。
                return getFromCache(k);
            else if (error instanceof UnknownKeyException)  // 3 如果消息来源说密钥未知，请创建一个新条目。
                return registerNewEntry(k, "DEFAULT");
            else
                return Flux.error(error); // 4 在所有其他情况下，“重新投掷”。
        })
    );
```

---

### 动态回退值

&emsp;&emsp;即使您没有其他（更安全的）方法来处理您的数据，您也可能希望根据收到的异常计算回退值。这相当于“捕获并动态计算回退值”。

&emsp;&emsp;例如，如果您的返回类型 (`MyWrapper`) 有一个专用于保存异常的变体（想想 `Future.complete(T success)` 与 `Future.completeExceptionally(Throwable error)`），您可以实例化错误保存变体并传递异常。

&emsp;&emsp;命令式示例如下所示：

```java
try {
  Value v = erroringMethod();
  return MyWrapper.fromValue(v);
}
catch (Throwable error) {
  return MyWrapper.fromError(error);
}
```

您可以通过使用 `onErrorResume` 和少量样板文件，以与回退方法解决方案相同的方式响应式地执行此操作，如下所示：

```java
erroringFlux.onErrorResume(error -> Mono.just(  // 1
        MyWrapper.fromError(error)  // 2
));
```

> 1 由于您期望错误的 `MyWrapper` 表示，因此您需要为 `onErrorResume` 获取 `Mono<MyWrapper>`。我们为此使用 Mono.just()
>
> 2 我们需要计算异常的值。在这里，我们通过使用相关的 `MyWrapper` 工厂方法包装异常来实现这一点。

---

### 捕捉并重新抛出

&emsp;&emsp;“捕获，包装到 `BusinessException`，然后重新抛出”在命令式世界中看起来像以下内容：

```java
try {
  return callExternalService(k);
}
catch (Throwable error) {
  throw new BusinessException("oops, SLA exceeded", error);
}
```

&emsp;&emsp;在“后备方法”示例中，`flatMap` 中的最后一行提示我们以反应方式实现相同的功能，如下所示：

```java
Flux.just("timeout1")
    .flatMap(k -> callExternalService(k))
    .onErrorResume(original -> Flux.error(
            new BusinessException("oops, SLA exceeded", original))
    );
```

&emsp;&emsp;然而，有一种更直接的方法可以使用`onErrorMap`实现相同的效果：

```java
Flux.just("timeout1")
    .flatMap(k -> callExternalService(k))
    .onErrorMap(original -> new BusinessException("oops, SLA exceeded", original));
```

---

### 侧面记录或反应

&emsp;&emsp;如果您希望错误继续传播但仍想在不修改序列的情况下对其做出反应（例如记录它），您可以使用 `doOnError` 运算符。这相当于“捕获、记录错误特定消息并重新抛出”模式，如以下示例所示：

```java
try {
  return callExternalService(k);
}
catch (RuntimeException error) {
  //make a record of the error
  log("uh oh, falling back, service failed for key " + k);
  throw error;
}
```

&emsp;&emsp;`doOnError` 运算符以及所有以 `doOn` 为前缀的运算符有时被称为具有“副作用”。它们让您可以在不修改序列事件的情况下窥视它们。

&emsp;&emsp;与前面显示的命令式示例一样，以下示例仍然传播错误，但确保我们至少记录外部服务出现故障：

```java
LongAdder failureStat = new LongAdder();
Flux<String> flux =
Flux.just("unknown")
    .flatMap(k -> callExternalService(k) // 1
        .doOnError(e -> {
            failureStat.increment();
            log("uh oh, falling back, service failed for key " + k); // 2
        })
        // 3
    );
```

> 1 可能失败的外部服务调用……
>
> 2 ......装饰有日志记录和统计副作用......
>
> 3 …之后，它仍然以错误终止，除非我们在这里使用错误恢复运算符。

&emsp;&emsp;我们还可以想象我们有统计计数器来增加作为第二个错误副作用。

---

### 使用资源和 Finally 块

&emsp;&emsp;最后一个与命令式编程相似的是清理，可以通过使用“使用 `finally` 块来清理资源”或使用“`Java 7 try-with-resource` 构造”来完成，如下所示：

&emsp;&emsp;示例 14. `finally` 的命令式使用

```java
Stats stats = new Stats();
stats.startTimer();
try {
  doSomethingDangerous();
}
finally {
  stats.stopTimerAndRecordTiming();
}
```

&emsp;&emsp;示例 15. 命令式使用 `try-with-resource`

```java
try (SomeAutoCloseable disposableInstance = new SomeAutoCloseable()) {
  return disposableInstance.toString();
}
```

&emsp;&emsp;两者都有对应的 Reactor：`doFinally` 和 `using`。

&emsp;&emsp;`doFinally` 是关于您希望在序列终止（使用 `onComplete` 或 `onError`）或被取消时执行的副作用。它会提示您哪种终止会触发副作用。以下示例显示如何使用 `doFinally`：

&emsp;&emsp;Reactive finally：`doFinally()`

```java
Stats stats = new Stats();
LongAdder statsCancel = new LongAdder();

Flux<String> flux =
Flux.just("foo", "bar")
    .doOnSubscribe(s -> stats.startTimer())
    .doFinally(type -> { // 1 doFinally 使用 SignalType 作为终止类型。
        stats.stopTimerAndRecordTiming(); // 2 与 finally 块类似，我们总是记录时间。
        if (type == SignalType.CANCEL) // 3 在这里，我们还仅在取消的情况下增加统计信息。
          statsCancel.increment();
    })
    .take(1);  // 4 take(1) 从上游请求 1，并在发出一个项目后取消。
```

&emsp;&emsp;另一方面，using 处理 Flux 从资源派生的情况，并且无论何时完成处理都必须对该资源进行操作。在下面的示例中，我们将“try-with-resource”的 AutoCloseable 接口替换为 Disposable：

&emsp;&emsp;例子 16. Disposable 资源

```java
AtomicBoolean isDisposed = new AtomicBoolean();
Disposable disposableInstance = new Disposable() {
    @Override
    public void dispose() {
        isDisposed.set(true);  // 4 在订阅和执行序列之后，isDisposed 原子布尔值变为真。
    }

    @Override
    public String toString() {
        return "DISPOSABLE";
    }
};
```

&emsp;&emsp;现在我们可以在其上执行与“try-with-resource”等效的响应式操作，如下所示：

&emsp;&emsp;示例 17. 响应式 try-with-resource：using()

```java
Flux<String> flux =
Flux.using(
        () -> disposableInstance, // 1 第一个 lambda 生成资源。在这里，我们返回模拟的 Disposable。
        disposable -> Flux.just(disposable.toString()), // 2 第二个 lambda 处理资源，返回 Flux<T>。
        Disposable::dispose // 3 当 <2> 的 Flux 终止或取消时调用第三个 lambda，以清理资源
);
```

---

### 演示 `onError` 的终端方面

&emsp;&emsp;为了演示所有这些运算符都会在发生错误时导致上游原始序列终止，我们可以使用一个更直观的示例，其中包含 Flux.interval。间隔运算符每 x 个时间单位标记一个递增的 Long 值。以下示例使用区间运算符：

```java
Flux<String> flux =
Flux.interval(Duration.ofMillis(250))
    .map(input -> {
        if (input < 3) return "tick " + input;
        throw new RuntimeException("boom");
    })
    .onErrorReturn("Uh oh");

flux.subscribe(System.out::println);
Thread.sleep(2100); // 1
```

> 1 请注意，默认情况下，interval 在计时器 Scheduler (Schedulers.parallel())上执行。如果我们想在主类中运行该示例，我们需要在此处添加睡眠调用，以便应用程序不会在没有产生任何值的情况下立即退出。

&emsp;&emsp;前面的示例每 250 毫秒打印一行，如下所示：

```java
tick 0
tick 1
tick 2
Uh oh
```

&emsp;&emsp;即使多了一秒钟的运行时间，间隔中也不再有滴答声。该序列确实因错误而终止。

---

### 重试

&emsp;&emsp;关于错误处理，还有另一个值得关注的运算符，在上一节中描述的情况下，您可能会想使用它。重试，顾名思义，让您重试产生错误的序列。

&emsp;&emsp;要记住的是，它通过重新订阅上游 Flux 来工作。这真是一个不同的序列，原来的还是终止了。为了验证这一点，我们可以重新使用前面的示例并附加一个 `retry(1)` 来重试一次，而不是使用 `onErrorReturn`。以下示例显示了如何执行此操作：

```java
Flux.interval(Duration.ofMillis(250))
    .map(input -> {
        if (input < 3) return "tick " + input;
        throw new RuntimeException("boom");
    })
    .retry(1)
    .elapsed() // 1 elapsed 将每个值与自上一个值发出以来的持续时间相关联。
    .subscribe(System.out::println, System.err::println); // 2 我们还想看看什么时候有 onError。

Thread.sleep(2100); // 3 确保我们有足够的时间来进行 4x2 刻度。
```

&emsp;&emsp;前面的示例产生以下输出：

```java
259,tick 0
249,tick 1
251,tick 2
506,tick 0  //  一个新的时间间隔从第 0 个滴答开始。额外的 250 毫秒持续时间来自第 4 个滴答，即导致异常和随后重试的那个。
248,tick 1
253,tick 2
java.lang.RuntimeException: boom
```

&emsp;&emsp;从前面的例子可以看出，`retry(1)` 只是重新订阅了一次原始间隔，从 0 重新开始计时。第二次，由于异常仍然发生，它放弃并将错误传播到下游。

&emsp;&emsp;有一个更高级的重试版本（称为 `retryWhen`），它使用“伴随”`Flux` 来判断特定失败是否应该重试。这个伴随的 `Flux` 由操作员创建但由用户装饰，以自定义重试条件。

&emsp;&emsp;伴随的 `Flux` 是一个 `Flux<RetrySignal>`，它被传递给重试策略/函数，作为 `retryWhen` 的唯一参数提供。作为用户，您定义该函数并使其返回一个新的 `Publisher<?>`。 `Retry` 类是一个抽象类，但如果您想使用简单的 `lambda (Retry.from(Function))` 转换伴侣，它会提供一个工厂方法。

&emsp;&emsp;重试周期如下：

- 每次发生错误时（可能会重试），都会将 `RetrySignal` 发射到已由您的函数修饰的伴随 `Flux` 中。在这里使用 `Flux` 可以鸟瞰到目前为止的所有尝试。 `RetrySignal` 提供对错误及其周围元数据的访问。
- 如果伴随 `Flux` 发出一个值，则会发生重试。
- 如果伴随的 `Flux` 完成，则错误被吞没，重试周期停止，结果序列也完成。
- 如果伴随的 Flux 产生错误 (`e`)，则重试循环停止并且结果序列错误为 `e`。

&emsp;&emsp;前两种情况的区别很重要。简单地完成同伴将有效地吞下一个错误。考虑以下使用 `retryWhen` 模拟 `retry(3)` 的方法：

```java
Flux<String> flux = Flux
    .<String>error(new IllegalArgumentException()) // 1 这会不断产生错误，需要重试。
    .doOnError(System.out::println) // 2 重试之前的 doOnError 让我们记录并查看所有失败。
    .retryWhen(Retry.from(companion -> // 3 Retry 改编自一个非常简单的函数 lambda
        companion.take(3))); // 4 在这里，我们将前三个错误视为可重试 (take(3))，然后放弃。
```

&emsp;&emsp;实际上，前面的示例会生成一个空的 Flux，但它会成功完成。由于同一 Flux 上的 retry(3) 会因最新错误而终止，因此此 retryWhen 示例与 retry(3) 并不完全相同。

&emsp;&emsp;获得相同的行为涉及一些额外的技巧：

```java
AtomicInteger errorCount = new AtomicInteger();
Flux<String> flux =
		Flux.<String>error(new IllegalArgumentException())
				.doOnError(e -> errorCount.incrementAndGet())
				.retryWhen(Retry.from(companion -> // 1
						companion.map(rs -> { // 2
							if (rs.totalRetries() < 3) return rs.totalRetries(); // 3
							else throw Exceptions.propagate(rs.failure()); // 4
						})
				));
```

> 1 我们通过从函数 `lambda` 进行调整而不是提供具体类来自定义 `Retry`
>
> 2 `companion` 发出 `RetrySignal` 对象，其中包含到目前为止的重试次数和上次失败
>
> 3 为了允许重试 3 次，我们考虑索引 < 3 并返回一个值以发出（这里我们只返回索引）。
>
> 4 为了错误地终止序列，我们在这三次重试后抛出原始异常。

> 可以使用 `Retry` 中公开的构建器以更流畅的方式以及更精细调整的重试策略来实现相同目的。例如：`errorFlux.retryWhen(Retry.max(3));`。
>
> 您可以使用类似的代码来实现“指数退避和重试”模式，如[常见问题解答](https://projectreactor.io/docs/core/release/reference/#faq.exponentialBackoff)中所示。

&emsp;&emsp;核心提供的重试助手 `RetrySpec` 和 `RetryBackoffSpec` 都允许高级自定义，例如：

- 为可以触发重试的异常设置过滤器（谓词）
- 通过 `modifyErrorFilter(Function)` 修改这样一个先前设置的过滤器
- 触发副作用，如记录重试触发器（即延迟前后的退避），前提是重试已验证（`doBeforeRetry()` 和 `doAfterRetry()` 是累加的）
- 在重试触发器周围触发异步 `Mono<Void>` ，它允许在基本延迟之上添加异步行为，但会进一步延迟触发器（`doBeforeRetryAsync` 和 `doAfterRetryAsync` 是附加的）
- 通过 `onRetryExhaustedThrow(BiFunction)` 在达到最大尝试次数时自定义异常。默认使用`Exceptions.retryExhausted(…)`，可以用`Exceptions.isRetryExhausted(Throwable)`来区分
- 激活瞬态错误的处理（见下文）

##### 重试暂时性错误

&emsp;&emsp;一些长期存在的源可能会看到零星的错误爆发，然后是一段较长的时间，在此期间一切都在平稳运行。本文档将这种错误模式称为暂时性错误。

&emsp;&emsp;在这种情况下，最好单独处理每个突发，这样下一个突发就不会继承前一个突发的重试状态。例如，使用指数退避策略，每个后续突发应该从最小退避持续时间开始延迟重试尝试，而不是从不断增长的退避持续时间开始。

&emsp;&emsp;代表 `retryWhen` 状态的 `RetrySignal` 接口具有可用于此目的的 `totalRetriesInARow()` 值。与通常的单调递增的 `totalRetries()` 索引不同，每次通过重试从错误中恢复时（即，当重试尝试导致传入的 `onNext` 而不是再次出现 `onError` 时），此二级索引都会重置为 0。

&emsp;&emsp;在 `RetrySpec` 或 `RetryBackoffSpec` 中将 `transientErrors(boolean)` 配置参数设置为 `true` 时，生成的策略会使用该 `totalRetriesInARow()` 索引，从而有效地处理瞬态错误。这些规范根据索引计算重试模式，因此实际上规范的所有其他配置参数都独立应用于每个突发错误。

```java
AtomicInteger errorCount = new AtomicInteger(); // 1
Flux<Integer> transientFlux = httpRequest.get() // 2
        .doOnError(e -> errorCount.incrementAndGet());

transientFlux.retryWhen(Retry.max(2).transientErrors(true)) // 3 
             .blockLast();
assertThat(errorCount).hasValue(6); // 4
```

> 1 我们将计算重试序列中的错误数以供说明。
>
> 2 我们假设一个 http 请求源，例如。一个流端点，有时会连续失败两次，然后恢复。
>
> 3 我们在该源上使用 `retryWhen`，配置为最多 2 次重试，但处于 `transientErrors` 模式。
>
> 4 最后，在 `errorCount` 中注册了 6 次尝试后，实现了有效响应并且 `transientFlux` 成功完成。

&emsp;&emsp;如果没有 `transientErrors(true)`，第二次突发将超过配置的最大尝试次数 2，整个序列最终将失败。

&emsp;&emsp;如果您想在没有实际 http 远程端点的情况下在本地尝试此操作，您可以将伪 `httpRequest` 方法实现为`Supplier`，如下所示：

```java
final AtomicInteger transientHelper = new AtomicInteger();
Supplier<Flux<Integer>> httpRequest = () ->
    Flux.generate(sink -> { // 1
        int i = transientHelper.getAndIncrement();
        if (i == 10) { // 2
            sink.next(i);
            sink.complete();
        }
        else if (i % 3 == 0) { // 3 
            sink.next(i);
        }
        else {
            sink.error(new IllegalStateException("Transient error at " + i)); // 4
        }
    });
```

> 1 我们生成了一个包含突发错误的源。
>
> 2 当计数器达到 10 时，它将成功完成。
>
> 3 如果 transientHelper atomic 是 3 的倍数，我们将发出 onNext 并因此结束当前突发。
>
> 4 在其他情况下，我们会发出一个 onError。那是 3 次中的 2 次，所以 2 次 onError 的爆发被 1 次 onNext 打断了。
