# 处理运算符或函数中的异常

&emsp;&emsp;通常，所有运算符本身都可能包含可能触发异常或调用可能同样失败的用户定义回调的代码，因此它们都包含某种形式的错误处理。

&emsp;&emsp;根据经验，未经检查的异常总是通过 `onError` 传播。例如，在 map 函数中抛出 `RuntimeException` 会转换为 `onError` 事件，如以下代码所示：

```java
Flux.just("foo")
    .map(s -> { throw new IllegalArgumentException(s); })
    .subscribe(v -> System.out.println("GOT VALUE"),
               e -> System.out.println("ERROR: " + e));
```

&emsp;&emsp;前面的代码打印出以下内容：

```bash
ERROR: java.lang.IllegalArgumentException: foo
```

> 您可以通过使用挂钩在将异常传递给 `onError` 之前对其进行调整。

&emsp;&emsp;然而，Reactor 定义了一组总是被认为是致命的异常（例如 `OutOfMemoryError`）。请参阅 `Exceptions.throwIfFatal` 方法。这些错误意味着 Reactor 无法继续运行并被抛出而不是传播。

> 在内部，还有一些情况仍然无法传播未经检查的异常（最明显的是在订阅和请求阶段），因为并发竞争可能导致双重 `onError` 或 `onComplete` 条件。当这些竞争发生时，无法传播的错误将被“丢弃”。这些情况仍然可以通过使用可定制的挂钩在某种程度上进行管理。请参阅[丢弃钩子](https://projectreactor.io/docs/core/release/reference/#hooks-dropping)。

&emsp;&emsp;你可能会问：“检查异常呢？”

&emsp;&emsp;例如，如果您需要调用一些声明它抛出异常的方法，您仍然必须在 `try-catch` 块中处理这些异常。不过，您有多种选择：

- 捕获异常并从中恢复。序列正常继续。
- 捕获异常，将其包装成未经检查的异常(运行时异常)，然后将其抛出（中断序列）。 `Exceptions` 实用程序类可以帮助您解决这个问题（我们接下来会讲到）。
- 如果您需要返回一个 `Flux`（例如，您在一个 `flatMap` 中），请将异常包装在一个产生错误的 `Flux` 中，如下所示：`return Flux.error(checkedException)`。 （序列也终止。）

&emsp;&emsp;`Reactor` 有一个 `Exceptions` 实用程序类，您可以使用它来确保仅在检查异常时才包装异常：

- 如有必要，使用 `Exceptions.propagate` 方法包装异常。它还首先调用 `throwIfFatal` 并且不包装 `RuntimeException`。
- 使用 `Exceptions.unwrap` 方法获取原始未包装的异常（返回到反应器特定异常层次结构的根本原因）。

&emsp;&emsp;考虑以下使用可抛出 `IOException` 的转换方法的映射示例：

```java
public String convert(int i) throws IOException {
    if (i > 3) {
        throw new IOException("boom " + i);
    }
    return "OK " + i;
}
```

&emsp;&emsp;现在假设您想在map中使用该方法。您现在必须显式捕获异常，并且您的 map 函数不能重新抛出它。因此，您可以将其作为 `RuntimeException` 传播到地图的 onError 方法，如下所示：

```java
Flux<String> converted = Flux
    .range(1, 10)
    .map(i -> {
        try { return convert(i); }
        catch (IOException e) { throw Exceptions.propagate(e); }
    });
```

&emsp;&emsp;稍后，当订阅前面的 `Flux` 并对错误做出反应时（例如在 `UI` 中），如果你想对 `IOExceptions` 做一些特殊的事情，你可以恢复到原来的异常。以下示例显示了如何执行此操作：

```java
converted.subscribe(
    v -> System.out.println("RECEIVED: " + v),
    e -> {
        if (Exceptions.unwrap(e) instanceof IOException) {
            System.out.println("Something bad happened with I/O");
        } else {
            System.out.println("Something bad happened");
        }
    }
);
```

